### ISSUE TITLE
Fix return type for methods

### ISSUE THREAD

**Issue by forevermatt** [silinternational/zxcvbn-api-client-php#1]
The return type (in the doc. comment) for `Score->getFull()` (and presumably the other method) is currently array, but what it actually returns is a Guzzle class (I forget which), that has a `toArray()` method.

It would be good to either add a wrapper method that converts the result to an actual array or change the doc. comment to reflect the real return type.

Example of where this was found: https://scrutinizer-ci.com/g/silinternational/idp-pw-api/inspections/e9156147-a1d3-466f-a127-5be81dd40f15/issues/files/application/common/helpers/Utils.php?status=failed&conditionIds%5B0%5D=197505

That Scrutinizer failure is also interfering with this PR (though the relevant line of code wasn't actually changed in that PR): https://github.com/silinternational/idp-pw-api/pull/74

**Comment by devon-sil** [comment]
Not worth our effort.
